### PR TITLE
Lab2

### PR DESCRIPTION
**Pull request by nchen269**

### CODE REVIEW

**Comment by pjiang99** [comment]
I found a mistake in 1 C), which I also had in my own report. When we average a discrete distribution, we don't scale up the probabilities. For example, when we are averaging over 3 days, we should divide the x values by 3. But we can't multiply each probability by 3 since that would make the sum of all probability 3 instead of 1.

**Comment by pjiang99** [comment]
For 2 a), I noticed that the areas under each of the curves you plotted were different, while they should actually all sum to 1. I think two factors caused this. One is that the distribution you chose has a quite weird behavior with the parameter you chose. You'll see what I mean if you run this code:
x1 = np.linspace(0,0.00000001,1000) 
l1= stats.lognorm.pdf(x1,5)
plt.plot(x1,l1)
The distribution you chose has a really high peak near x=0, so you could never catch its actual shape using x1 = np.linspace(0,10,35). I would recommend that you make the distribution smoother by using a parameter of something like 0.25 instead of 5.

The other is that you didn't normalize the scaling effect caused by np.convolve. np.convolve deals with discrete distributions. So if you using it on continuous distributions, you need to normalize the resulting probability densities with the step size you choose. For example,  when you wrote 
l2= np.convolve(l1,l1)*2,
you actually need
l2= np.convolve(l1,l1)*2 / ((10 - 0) / (35 - 1)),
since you used x1 = np.linspace(0,10,35).

Also, make sure to change your plot title from Rayleigh to lognormal.

**Comment by pjiang99** [comment]
For Problem 3, the lab specification says
"After flat-fielding, the background appears as a zero-mean Gaussian with constant width over the image."
So I think you may need a Gaussian with its mean = 0 instead of 4.

**Comment by SaranshPK** [comment]
I agree with Tianhao's comment about about your plots in 2.a. you should have more points in the domain so that you can fully capture the behavior of the rayleigh distribution and it's convolutions.

**Comment by nchen269** [comment]
@kentwils

**Comment by nchen269** [comment]
> For 2 a), I noticed that the areas under each of the curves you plotted were different, while they should actually all sum to 1. I think two factors caused this. One is that the distribution you chose has a quite weird behavior with the parameter you chose. You'll see what I mean if you run this code:
> x1 = np.linspace(0,0.00000001,1000)
> l1= stats.lognorm.pdf(x1,5)
> plt.plot(x1,l1)
> The distribution you chose has a really high peak near x=0, so you could never catch its actual shape using x1 = np.linspace(0,10,35). I would recommend that you make the distribution smoother by using a parameter of something like 0.25 instead of 5.
> 
> The other is that you didn't normalize the scaling effect caused by np.convolve. np.convolve deals with discrete distributions. So if you using it on continuous distributions, you need to normalize the resulting probability densities with the step size you choose. For example, when you wrote
> l2= np.convolve(l1,l1)*2,
> you actually need
> l2= np.convolve(l1,l1)*2 / ((10 - 0) / (35 - 1)),
> since you used x1 = np.linspace(0,10,35).
> 
> Also, make sure to change your plot title from Rayleigh to lognormal.

**Pull request closed without merging**
